apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namespace: roboshop
data:
  MYSQL_HOST: "mysql"
  #MYSQL_USER: "root"
  MYSQL_PASSWORD: "root"
  MYSQL_DATABASE: "lms"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: roboshop
  labels: # these labels are deployment labels
    app: web
    project: roboshop
    tier: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
      project: roboshop
      tier: web
  template:
    metadata:
      labels:
        app: web
        project: roboshop
        tier: web
    spec:
      containers:
      - name: web
        image: suryashankar598/flaskappnew1:v1
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: mysql

---

apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: roboshop
spec:
  selector:
    app: web
    project: roboshop
    tier: web
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer  # Change to LoadBalancer if using a cloud provider that supports it
